Repository mmasias/23-24-prg1, pull requests merged in 2023-10, with the labels that each got.

#30 aresHéctor
  entregas/aresHéctor/reto-001/CambioDinero.java
  entregas/aresHéctor/reto-002/CambioDinero2.java
  entregas/aresHéctor/reto-003/CambioDinero3.java
  entregas/aresHéctor/reto-004/FormarNumero.java
  entregas/aresHéctor/reto-005/MayorNumero.java
Labels: Recibido

#20 retos_1_2_3_4_5
  entregas/becerrilCelia/Reto-001/CambioDinero.java
  entregas/becerrilCelia/Reto-002/CambioDinero2.java
  entregas/becerrilCelia/Reto-002/reto2.txt
  entregas/becerrilCelia/Reto-003/DevolverCambioMejorado.java
  entregas/becerrilCelia/Reto-004/DeconstruccionNumero.java
  entregas/becerrilCelia/Reto-005/DeterminarMayor.java
Labels: Recibido

#18 Primera entrega
  entregas/DeCosSaul/reto-001/Reto1.java
  entregas/DeCosSaul/reto-002/Reto2.java
  entregas/DeCosSaul/reto-003/Reto3.java
  entregas/DeCosSaul/reto-004/Reto4.java
  entregas/DeCosSaul/reto-005/Reto5.java
Labels: Recibido

#21 Primera entrega
  entregas/maciejewskiBruno/reto-001/Tienda.java
  entregas/maciejewskiBruno/reto-002/TiendaMejorada.java
  entregas/maciejewskiBruno/reto-003/TiendaMejorada2.java
  entregas/maciejewskiBruno/reto-004/Deconstruccion.java
  entregas/maciejewskiBruno/reto-005/NumeroMayor.java
Labels: Recibido

#50 Retos Liam con arreglos
  entregas/andersonLiam/reto-001/Reto1.java
  entregas/andersonLiam/reto-002/Reto2.java
  entregas/andersonLiam/reto-003/Reto3.java
  entregas/andersonLiam/reto-004/Reto4.java
  entregas/andersonLiam/reto-005/Reto5.java
Labels: Recibido, :+1:

#67 Retos 1 a 5 (más el último pero con "if" y "else")
  entregas/arronizMaria/Reto001/reto001.java
  entregas/arronizMaria/Reto002/reto002.java
  entregas/arronizMaria/Reto003/reto003.java
  entregas/arronizMaria/Reto004/reto004.java
  entregas/arronizMaria/Reto005 (if)/reto0052.java
  entregas/arronizMaria/Reto005/reto005.java
Labels: Recibido, :+1:

#66 RETOS JAVA
  entregas/gutierrezMarcos/reto-001/Cambio.java
  entregas/gutierrezMarcos/reto-002/DevolverCambio.java
  entregas/gutierrezMarcos/reto-003/DevolverCambioMejorado.java
  entregas/gutierrezMarcos/reto-004/Decostruccion.java
  entregas/gutierrezMarcos/reto-005/NumeroMayor.java
Labels: Recibido, :+1:

#70 Entrega Retos RecioLuca
  entregas/.vscode/settings.json
  entregas/recioLuca/Reto-001/Reto1.java
  entregas/recioLuca/Reto-002/Reto2.java
  entregas/recioLuca/Reto-003/Reto3.java
  entregas/recioLuca/Reto-004/Reto4.java
  entregas/recioLuca/Reto-005/Reto5.java
Labels: Recibido, :+1:

#71 retos_Nazaret_Deras
  entregas/ortizNazaret/reto001/Reto1_NazaretDeras.java
  entregas/ortizNazaret/reto002/Reto2_NazaretDeras.java
  entregas/ortizNazaret/reto003/Reto3_NazaretDeras.java
  entregas/ortizNazaret/reto004/Reto4_NazaretDeras.java
  entregas/ortizNazaret/reto005/Reto5_NazaretDeras.java
Labels: Recibido, :+1:

#87 RetosOscarPineda
  entregas/pinedaOscar/reto-001/DevolucionyCompra.java
  entregas/pinedaOscar/reto-002/DevolucionyCompra2.java
  entregas/pinedaOscar/reto-003/ScannerComprayDevolucion.java
  entregas/pinedaOscar/reto-004/ScannerDeconstruccionDeUnNumero.java
  entregas/pinedaOscar/reto-005/MenorOMayor.java
Labels: Recibido

#72 Retos Angel Romero
  entregas/README.md
  entregas/romeroAngel/reto-001/Reto001_romeroAngel.java
  entregas/romeroAngel/reto-002/Reto002_romeroAngel.java
  entregas/romeroAngel/reto-003/Reto003_romeroAngel.java
  entregas/romeroAngel/reto-004/Reto004_romeroAngel.java
  entregas/romeroAngel/reto-005/Reto005_romeroAngel.java
Labels: Recibido, :+1:

#73 Retos de Raúl Tascón
  entregas/tasconraul/Reto-004/Reto4.java
  entregas/tasconraul/reto-001/Reto1.java
  entregas/tasconraul/reto-002/Reto2.java
  entregas/tasconraul/reto-003/Reto3.java
  entregas/tasconraul/reto-005/Reto5.java
Labels: Recibido, :+1:, :warning:

#74 Retos Mario Osorio
  entregas/OsorioMario/reto-001/reto-001.java
  entregas/OsorioMario/reto-002/reto-002.java
  entregas/OsorioMario/reto-003/reto-003.java
  entregas/OsorioMario/reto-004/reto-004.java
  entregas/OsorioMario/reto-005/reto-005.java
Labels: Recibido, :warning:

#75 entrega-001
  entregas/barrosKelvia/reto-001/DevolverCambio.java
  entregas/barrosKelvia/reto-002/DevolverCambio2.java
  entregas/barrosKelvia/reto-003/DevolverCambioMejorado.java
  entregas/barrosKelvia/reto-004/Deconstruccion.java
  entregas/barrosKelvia/reto-005/NumeroMayor.java
Labels: Recibido, :+1:

#76 Entrega Retos
  entregas/moralesJosePablo/reto-001/Reto001.java
  entregas/moralesJosePablo/reto-002/Reto002.java
  entregas/moralesJosePablo/reto-003/Reto003.java
  entregas/moralesJosePablo/reto-004/Reto004.java
  entregas/moralesJosePablo/reto-005/Reto005.java
Labels: Recibido, :x:

#77 Entrega retos 1-5
  .DS_Store
  entregas/.DS_Store
  entregas/alejandroAteca/.DS_Store
  entregas/alejandroAteca/reto001/.DS_Store
  entregas/alejandroAteca/reto001/001-DevolverCambio.java
  entregas/alejandroAteca/reto002/002-DevolverCambio.java
  entregas/alejandroAteca/reto003/003-DevolverCambioMejorado.java
  entregas/alejandroAteca/reto004/004-Deconstruccion.java
  entregas/alejandroAteca/reto005/005-NumeroMayor.java
Labels: Recibido, :+1:

#79 retos1,2,3,4,5
  entregas/lavinLaura/reto-001/Reto1.java
  entregas/lavinLaura/reto-002/Reto2.java
  entregas/lavinLaura/reto-003/Reto3.java
  entregas/lavinLaura/reto-004/Reto4.java
  entregas/lavinLaura/reto-005/Reto5.java
Labels: Recibido, :warning:

#80 Retos Miguel Andecochea
  entregas/AndecocheaMiguel/Reto001/CompraDevolucion.java
  entregas/AndecocheaMiguel/Reto002/DevolverCambio.java
  entregas/AndecocheaMiguel/Reto003/DevolverCambioMejorado.java
  entregas/AndecocheaMiguel/Reto004/DeconstruccionNumero.java
  entregas/AndecocheaMiguel/Reto005/NumeroMayor.java
Labels: Recibido, :+1:, :warning:

#82 Entrega retos Francisco Venero
  entregas/veneroFrancisco/reto-001/reto1.java
  entregas/veneroFrancisco/reto-002/reto2.java
  entregas/veneroFrancisco/reto-003/reto3.java
  entregas/veneroFrancisco/reto-004/reto4.java
  entregas/veneroFrancisco/reto-005/reto5.java
Labels: Recibido, :+1:, :warning:

#83 Retos Programación
  entregas/lopezAndres/reto-001/DevolucionDinero.java
  entregas/lopezAndres/reto-002/DevolucionDinero2.java
  entregas/lopezAndres/reto-003/Reto3.java
  entregas/lopezAndres/reto-004/Reto004_lopezAndres.java
  entregas/lopezAndres/reto-005/Reto005_lopezAndres.java
Labels: Recibido, :+1:

#84 retos
  entregas/rodríguezSergio/Reto001/reto001_Sergio_Rodriguez.java
  entregas/rodríguezSergio/Reto002/reto002_Sergio_Rodriguez.java
  entregas/rodríguezSergio/Reto003/reto003_Sergio_Rodriguez.java
  entregas/rodríguezSergio/Reto004/reto004_Sergio_Rodriguez.java
  entregas/rodríguezSergio/Reto005/reto005_Sergio_Rodriguez.java
Labels: Recibido, :+1:, :warning:

#85 Reto del 01 al 05
  entregas/SaucedoIan/reto-001/Reto1.java
  entregas/SaucedoIan/reto-002/Reto02.java
  entregas/SaucedoIan/reto-003/Reto03.java
  entregas/SaucedoIan/reto-004/Reto04.java
  entregas/SaucedoIan/reto-005/Reto005.java
Labels: Recibido, :+1:, :warning:

#86 Entrega retos 001-005 corregido
  entregas/fondoJose/reto-003/CambioMejorado.java
  entregas/fondoJose/reto-004/DeconstruccionDeNumero.java
  entregas/fondoJose/reto-005/NumeroMayor.java
Labels: Recibido, :+1:

#96 reto-006
  entregas/maciejewskiBruno/reto-001/Tienda.java
  entregas/maciejewskiBruno/reto-002/TiendaMejorada.java
  entregas/maciejewskiBruno/reto-003/TiendaMejorada2.java
  entregas/maciejewskiBruno/reto-004/Deconstruccion.java
  entregas/maciejewskiBruno/reto-005/NumeroMayor.java
  entregas/maciejewskiBruno/reto-006/LeerMente.java
Labels: Recibido, :+1:

#100 Corrección de Retos 1-5 + Reto 6
  entregas/README.md
  entregas/romeroAngel/reto-001/MoneyCalculations.java
  entregas/romeroAngel/reto-002/MoneyCalculationsv2.java
  entregas/romeroAngel/reto-003/ScannerMoneyCalculationsv2.java
  entregas/romeroAngel/reto-004/DeconstructNumber.java
  entregas/romeroAngel/reto-005/DetermineGreater.java
  entregas/romeroAngel/reto-006/GuessNumber.java
Labels: Recibido, :+1:

#99 Adrian fdz17 patch 1
  README.md
  entregas/fernándezAdrián/Reto-04
  entregas/fernándezAdrián/reto-001/CalcularCambio.java
  entregas/fernándezAdrián/reto-002/DevolverCambio.java
  entregas/fernándezAdrián/reto-005
  entregas/fernándezAdrián/reto-03
  evaluacionContinua/README.md
  examenFinal/README.md
  examenParcial/README.md
  imagenes/cartas-numeros.png
  proyectos/README.md
  retos/006-AdivinarNumero/README.md
  retos/README.md
Labels: Recibido, :warning:, :x:

#97 Ericpolan03 patch 1
  entregas/polancoEric/reto-001/DevolverCambio.java
  entregas/polancoEric/reto-002/DevolverCambio.java
  entregas/polancoEric/reto-003/DevolverCambioMejorado.java
  entregas/polancoEric/reto-004/Deconstruccion.java
  entregas/polancoEric/reto-005/NumeroMayor.java
Labels: Recibido, :+1:

#101 Entrega 1 Reto 6
  linaresJaime/Reto-001/Reto001
  linaresJaime/Reto-002/Reto002
  linaresJaime/Reto-003/Reto003
  linaresJaime/Reto-004/Reto004
  linaresJaime/Reto-005/Reto005
  linaresJaime/Reto-006/Reto006
Labels: Recibido

#108 Reto 6 Liam
  entregas/Reto6.java
  entregas/andersonLiam/reto-001/Reto1.java
  entregas/andersonLiam/reto-002/Reto2.java
  entregas/andersonLiam/reto-003/Reto3.java
  entregas/andersonLiam/reto-004/Reto4.java
  entregas/andersonLiam/reto-005/Reto5.java
Labels: Recibido, :warning:

#113 Reto 6 Jorge Polidura
  entregas/poliduraJorge/reto-001/CalcularCambio.java
  entregas/poliduraJorge/reto-002/CalcularCambio.java
  entregas/poliduraJorge/reto-003/CalcularCambioMejorado.java
  entregas/poliduraJorge/reto-004/Deconstruccion.java
  entregas/poliduraJorge/reto-005/NumeroMayor.java
  entregas/poliduraJorge/reto-006/AdivinarNumero.java
Labels: Recibido, :warning:

#115 reto06
  entregas/ortizNazaret/reto-006/Tarjetas.java
  entregas/ortizNazaret/reto001/Reto1_NazaretDeras.java
  entregas/ortizNazaret/reto002/Reto2_NazaretDeras.java
  entregas/ortizNazaret/reto003/Reto3_NazaretDeras.java
  entregas/ortizNazaret/reto004/Reto4_NazaretDeras.java
  entregas/ortizNazaret/reto005/Reto5_NazaretDeras.java
Labels: Recibido, :+1:

#123 Entrega reto 006 Luca Recio
  entregas/.vscode/settings.json
  entregas/recioLuca/Reto-001/Reto1.java
  entregas/recioLuca/Reto-002/Reto2.java
  entregas/recioLuca/Reto-003/Reto3.java
  entregas/recioLuca/Reto-004/Reto4.java
  entregas/recioLuca/Reto-005/Reto5.java
  entregas/recioLuca/Reto-006/Reto6.java
Labels: Recibido, :warning:

#118 Reto 06
  entregas/SaucedoIan/reto-001/Reto1.java
  entregas/SaucedoIan/reto-002/Reto02.java
  entregas/SaucedoIan/reto-003/Reto03.java
  entregas/SaucedoIan/reto-004/Reto04.java
  entregas/SaucedoIan/reto-005/Reto005.java
  entregas/SaucedoIan/reto-006/reto06.java
Labels: Recibido, :+1:

#119 entrega reto 6
  entregas/alejandroAteca/reto006/006-AdivinarNumero.java
Labels: Recibido, :+1:

#122 Entrega reto 6
  entregas/AndecocheaMiguel/Reto001/CompraDevolucion.java
  entregas/AndecocheaMiguel/Reto002/DevolverCambio.java
  entregas/AndecocheaMiguel/Reto003/DevolverCambioMejorado.java
  entregas/AndecocheaMiguel/Reto004/DeconstruccionNumero.java
  entregas/AndecocheaMiguel/Reto005/NumeroMayor.java
  entregas/AndecocheaMiguel/Reto006/AdivinarNumero.java
Labels: Recibido

#124 Hector Ares reto 6
  entregas/aresHéctor/reto-001/CambioDinero.java
  entregas/aresHéctor/reto-002/CambioDinero2.java
  entregas/aresHéctor/reto-003/CambioDinero3.java
  entregas/aresHéctor/reto-004/FormarNumero.java
  entregas/aresHéctor/reto-005/MayorNumero.java
  entregas/aresHéctor/reto-006/AdivinarNumero.java
Labels: Recibido, :warning:

#125 entrega reto006 Javier
  entregas/javier.rodriguez/reto-001/CambioDinero1.java
  entregas/javier.rodriguez/reto-002/CambioDinero2.java
  entregas/javier.rodriguez/reto-003/CambioDinero3.java
  entregas/javier.rodriguez/reto-004/FormarNumero.java
  entregas/javier.rodriguez/reto-005/MayorNumero.java
  entregas/javier.rodriguez/reto-006/AdivinarNumero.java
Labels: Recibido, :warning:

#129 RETO 6
  entregas/reyPablo/Reto-006/Adivinarnumero.java
  entregas/reyPablo/reto-001/Reto1.java
  entregas/reyPablo/reto-002/Reto2.java
  entregas/reyPablo/reto-003/Reto3.java
  entregas/reyPablo/reto-004/Reto4.java
  entregas/reyPablo/reto-005/Reto5.java
Labels: Recibido, :warning:

#131 EntregaReto6- KommansClaudia
  entregas/kommansClaudia/reto-001/Reto1.java
  entregas/kommansClaudia/reto-002/Reto2.java
  entregas/kommansClaudia/reto-003/Reto3.java
  entregas/kommansClaudia/reto-004/Reto4.java
  entregas/kommansClaudia/reto-005/Reto5.java
  entregas/kommansClaudia/reto-006/Reto6.java
Labels: Recibido, :warning:

#132 Reto 006 Mario Viadero
  entregas/viaderoMario/reto 001/reto001.java
  entregas/viaderoMario/reto 002/reto002.java
  entregas/viaderoMario/reto 003/reto003.java
  entregas/viaderoMario/reto 004/reto004.java
  entregas/viaderoMario/reto 005/reto005
  entregas/viaderoMario/reto 005/reto005.java
  entregas/viaderoMario/reto 006/Reto006.java
Labels: Recibido

#133 Reto006
  entregas/moralesJosePablo/reto-001/Reto001.java
  entregas/moralesJosePablo/reto-002/Reto002.java
  entregas/moralesJosePablo/reto-003/Reto003.java
  entregas/moralesJosePablo/reto-004/Reto004.java
  entregas/moralesJosePablo/reto-005/Reto005.java
  entregas/moralesJosePablo/reto-006/Reto006.java
Labels: Recibido

#136 reto 6 laura
  entregas/lavinLaura/reto-001/Reto1.java
  entregas/lavinLaura/reto-002/Reto2.java
  entregas/lavinLaura/reto-003/Reto3.java
  entregas/lavinLaura/reto-004/Reto4.java
  entregas/lavinLaura/reto-005/Reto5.java
  entregas/lavinLaura/reto-006/Reto6.java
Labels: Recibido, :warning:

#137 Reto-006 (María Arroniz)
  entregas/arronizMaria/Entrega-001/Reto001/reto001.java
  entregas/arronizMaria/Entrega-001/Reto002/reto002.java
  entregas/arronizMaria/Entrega-001/Reto003/reto003.java
  entregas/arronizMaria/Entrega-001/Reto004/reto004.java
  entregas/arronizMaria/Entrega-001/Reto005 (if)/reto0052.java
  entregas/arronizMaria/Entrega-001/Reto005/reto005.java
  entregas/arronizMaria/Entrega-002/Reto-006/Tarjetas.java
Labels: Recibido, :+1:

#138 Reto 6 Adivinar Número
  entregas/lopezAndres/reto-001/DevolucionDinero.java
  entregas/lopezAndres/reto-002/DevolucionDinero2.java
  entregas/lopezAndres/reto-003/Reto3.java
  entregas/lopezAndres/reto-004/Reto004_lopezAndres.java
  entregas/lopezAndres/reto-005/Reto005_lopezAndres.java
  entregas/lopezAndres/reto-006/reto6_adivinarnumero.java
Labels: Recibido, :warning:

#152 Adrian fdz17 patch 1
  entregas/fernándezAdrián/Reto-04
  entregas/fernándezAdrián/reto-001/CalcularCambio.java
  entregas/fernándezAdrián/reto-002/DevolverCambio.java
  entregas/fernándezAdrián/reto-005
  entregas/fernándezAdrián/reto-006
  entregas/fernándezAdrián/reto-03
Labels: Recibido, :x:

#140 Camila Palma: Reto-006
  entregas/palmaCamila/reto001/DevolverCambio.java
  entregas/palmaCamila/reto002/CambioMejorado.java
  entregas/palmaCamila/reto003/DevolverCambioMejorado.java
  entregas/palmaCamila/reto004/Desconstruccion.java
  entregas/palmaCamila/reto005/NumeroMayor.java
  entregas/palmaCamila/reto006/LecturaCartas.java
Labels: Recibido, :+1:, :warning:
